[package]
name = "dqn_trader"
version = "0.1.0"
edition = "2021"

[dependencies]
# Tokio for async runtime
tokio = { version = "1", features = ["full"] }

# Reqwest for making HTTP requests
reqwest = { version = "0.11", features = ["json"] }

# Serde for serialization and deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# tch-rs (PyTorch bindings for Rust) for model creation
tch = "0.4"

# Chrono for date and time handling
chrono = "0.4"

# Rand for random number generation
rand = "0.8"

# Serde for handling JSON serialization
serde = { version = "1.0", features = ["derive"] }

# SliceRandom for random sampling (used in replay buffer sampling)
rand = "0.8"

# Mutex for synchronization in async tasks
tokio = { version = "1", features = ["sync"] }

[dependencies]
# Add this if you want the ability to work with async and sync Mutex concurrently
tokio = { version = "1", features = ["full"] }

# Optionally, for better logging during development
log = "0.4"
env_logger = "0.9"
