name: Automated Training and Data Fetching

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust version as needed

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training and Data Fetching
        env:
          PYTHONUNBUFFERED: 1  # Ensures real-time log output
        run: |
          echo "Starting main process..."
          nohup python3 main.py > main.log 2>&1 &
          echo "Process running in background with PID $(pgrep -f 'python3 main.py')"

      - name: Monitor Logs
        if: always()
        run: |
          echo "Checking recent logs..."
          tail -n 50 main.log || echo "No logs found."

      - name: Cleanup Background Process
        if: always()
        run: |
          echo "Stopping background process if running..."
          PID=$(pgrep -f "python3 main.py")
          if [ -n "$PID" ]; then
            kill -9 $PID || echo "Failed to stop process with PID $PID"
          else
            echo "No running process found."

      - name: Upload Best Model as Artifact
        if: always()
        run: |
          echo "Uploading best model artifact..."
          if [ -f "best_dqn_model.pth" ]; then
            echo "Best model found, uploading..."
            tar -czf best_dqn_model.tar.gz best_dqn_model.pth
            echo "Artifact created: best_dqn_model.tar.gz"
          else
            echo "No best model found to upload."
            exit 1
          fi

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: best_dqn_model
          path: best_dqn_model.tar.gz